PidFile /tmp/c-icap.pid
CommandsSocket /tmp/c-icap.ctl

Timeout 300
MaxKeepAliveRequests 100
StartServers 1
MaxServers 2
MinSpareThreads 1
MaxSpareThreads 4
ThreadsPerChild 4
MaxRequestsPerChild 0

Port 1344
User c-icap
Group c-icap
ServerAdmin you@example.local
ServerName c-icap.local
TmpDir /tmp

ModulesDir /usr/lib/x86_64-linux-gnu/c_icap
ServicesDir /usr/lib/x86_64-linux-gnu/c_icap

Service echo srv_echo.so
